#druid 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?userEncoding=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
  # 禁止缓存，生产环境要开启
  thymeleaf:
    cache: false

logging:
  level:
    com.dodo.mblog.mapper: debug
server:
  port: 8080


